coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0001}
    params: {dataset: iNaturalist18, feat_dim: 2048, log_dir: ./logs/iNaturalist18/models/resnet50_uniform_e90,
      num_classes: 8142, stage1_weights: false}
  feat_model:
    def_file: ./models/ResNet50Feature.py
    fix: false
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0001}
    params: {dataset: iNaturalist18, dropout: null, log_dir: ./logs/iNaturalist18/models/resnet50_uniform_e90,
      stage1_weights: false, use_fc: false, use_selfatt: false}
shuffle: false
training_opt:
  backbone: resnet50
  batch_size: 512
  dataset: iNaturalist18
  display_step: 10
  feature_dim: 2048
  log_dir: ./logs/iNaturalist18/models/resnet50_uniform_e90
  log_root: ./logs/iNaturalist18
  num_classes: 8142
  num_epochs: 90
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 30}
  stage: resnet50_uniform_e90
  sub_dir: models
